# Generated by Django 2.2.5 on 2019-12-05 12:59

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(users.models.USER_TYPE('RG'), 'RG'), (users.models.USER_TYPE('TK'), 'TK')], default='RG', max_length=2),
        ),
    ]
