# Generated by Django 2.2.8 on 2019-12-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20191205_0959"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("RG", "RG"), ("TK", "TK")], default="RG", max_length=2
            ),
        ),
    ]
