# Generated by Django 2.2.10 on 2020-03-27 16:28

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200302_1647'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
