# Generated by Django 2.2.5 on 2019-10-13 13:18

from django.db import migrations


def create_collective_chat(apps, schema_editor):
    Chat = apps.get_model("chats.Chat")
    Chat.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_message"),
    ]

    operations = [migrations.RunPython(create_collective_chat)]
